enum ACTION_TYPES {
    SET_TRACKS_DATA = '@ORTALIOMUSIC/SET_TRACKS_DATA',
    PLAY_PAUSE_TRACK = '@ORTALIOMUSIC/PLAY_PAUSE_TRACK',
    PLAY_PAUSE_TRACK_SUCCESS = '@ORTALIOMUSIC/PLAY_PAUSE_TRACK_SUCCESS',
    PLAY_PAUSE_TRACK_FAILURE = '@ORTALIOMUSIC/PLAY_PAUSE_TRACK_FAILURE',
    STOP_PLAYBACK = '@ORTALIOMUSIC/STOP_PLAYBACK',
    SET_TRACK_PROGRESS = '@ORTALIOMUSIC/SET_TRACK_PROGRESS',
    TRACK_SEEK_TO = '@ORTALIOMUSIC/TRACK_SEEK_TO',
    TRACK_SEEK_TO_SUCCESS = '@ORTALIOMUSIC/TRACK_SEEK_TO_SUCCESS',
    TOGGLE_VOLUME = '@ORTALIOMUSIC/TOGGLE_VOLUME',
}
export default ACTION_TYPES;
