enum ACTION_TYPES {
    SET_TRACKS_DATA = '@ORTALIOMUSIC/SET_TRACKS_DATA',
    PLAY_PAUSE_TRACK = '@ORTALIOMUSIC/PLAY_PAUSE_TRACK',
    PLAY_PAUSE_TRACK_SUCCESS = '@ORTALIOMUSIC/PLAY_PAUSE_TRACK_SUCCESS',
    PLAY_PAUSE_TRACK_FAILURE = '@ORTALIOMUSIC/PLAY_PAUSE_TRACK_FAILURE',
}
export default ACTION_TYPES;
